windows:
- geometry: !!binary |
    AdnQywACAAAAAAAKAAAApAAAA7oAAAPyAAAACwAAAKQAAAO5AAAD8QAAAAAAAAAAB4A=
  tabs:
  - active: true
    history:
    - original-url: https://duckduckgo.com/?q=webkit%20vs%20webengine%20qutebrowser
      pinned: false
      title: https://duckduckgo.com/?q=webkit+vs+webengine+qutebrowser&ia=qa
      url: https://duckduckgo.com/?q=webkit+vs+webengine+qutebrowser&ia=qa
    - original-url: https://duckduckgo.com/?q=webkit+vs+web+engine+%22qutebrowser%22
      pinned: false
      title: https://duckduckgo.com/?q=webkit+vs+web+engine+%22qutebrowser%22&ia=web
      url: https://duckduckgo.com/?q=webkit+vs+web+engine+%22qutebrowser%22&ia=web
    - original-url: https://duckduckgo.com/?q=qutebrowser%20editor%20command
      pinned: false
      title: https://duckduckgo.com/?q=qutebrowser+editor+command&ia=web
      url: https://duckduckgo.com/?q=qutebrowser+editor+command&ia=web
    - pinned: false
      title: qutebrowser editor command - Google Search
      url: https://encrypted.google.com/search?hl=en&q=qutebrowser%20editor%20command
    - pinned: false
      title: qutebrowser editor command - Google Search
      url: https://encrypted.google.com/search?q=qutebrowser+editor+command&hl=en&ei=AGpBWr-rOeGB0gLJuaa4Dw&start=10&sa=N
    - pinned: false
      title: qutebrowser editor command - Google Search
      url: https://encrypted.google.com/search?q=qutebrowser+editor+command&hl=en&ei=AGpBWr-rOeGB0gLJuaa4Dw&start=11&sa=N
    - pinned: false
      title: qutebrowser editor command - Google Search
      url: https://encrypted.google.com/search?q=qutebrowser+editor+command&hl=en&ei=AGpBWr-rOeGB0gLJuaa4Dw&start=12&sa=N
    - pinned: false
      title: qutebrowser editor command - Google Search
      url: https://encrypted.google.com/search?q=qutebrowser+editor+command&hl=en&ei=JG1BWqORD5WyjwOjv7SACg&start=22&sa=N&biw=1010&bih=510
    - pinned: false
      title: qutebrowser editor command - Google Search
      url: https://encrypted.google.com/search?q=qutebrowser+editor+command&hl=en&ei=JG1BWqORD5WyjwOjv7SACg&start=22&sa=N&biw=1010&bih=511
    - pinned: false
      title: qutebrowser editor command - Google Search
      url: https://encrypted.google.com/search?q=qutebrowser+editor+command&hl=en&biw=1010&bih=511&ei=Rm1BWv-mDdX0jwPxyYf4BA&start=32&sa=N
    - pinned: false
      title: qutebrowser editor command - Google Search
      url: https://encrypted.google.com/search?q=qutebrowser+editor+command&hl=en&biw=1010&bih=511&ei=l21BWqfLEs2ejwO3iq-QCg&start=42&sa=N
    - original-url: https://duckduckgo.com/?q=qutebrowser%20editor%20settings
      pinned: false
      title: qutebrowser editor settings at DuckDuckGo
      url: https://duckduckgo.com/?q=qutebrowser+editor+settings&ia=web
    - original-url: https://duckduckgo.com/?q=qutebrowser+editor+settings&ia=web
      pinned: false
      title: qutebrowser - A keyboard-driven, vim-like browser based on PyQt5 / Community
        Contributions / Arch Linux Forums
      url: https://bbs.archlinux.org/viewtopic.php?id=191076
    - pinned: false
      title: History
      url: qute://history/
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 47589
      title: TubeGalore – Free Porn Tubes
      url: https://www.tubegalore.com/az/
      zoom: 2.5
- geometry: !!binary |
    AdnQywACAAAAAAAKAAAApAAAA7oAAAPyAAAACwAAAKQAAAO5AAAD8QAAAAAAAAAAB4A=
  tabs:
  - active: true
    history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Triple Penetration tubes :: TubeGalore'
      url: https://www.tubegalore.com/c/triple-penetration
      zoom: 1.9
- geometry: !!binary |
    AdnQywACAAAAAAAKAAAApAAAA7oAAAPyAAAACwAAAKQAAAO5AAAD8QAAAAAAAAAAB4A=
  tabs:
  - active: true
    history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Tight tubes :: TubeGalore'
      url: https://www.tubegalore.com/c/tight
      zoom: 1.9
- geometry: !!binary |
    AdnQywACAAAAAAAKAAAEPwAAA7oAAAVvAAAACwAABD8AAAd0AAEELP////8AAAAAB4A=
  tabs:
  - active: true
    history:
    - pinned: false
      title: 'Tight Pussy tubes :: TubeGalore'
      url: https://www.tubegalore.com/c/tight-pussy
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 40
      title: 'Tight Pussy tubes :: TubeGalore'
      url: https://www.tubegalore.com/c/tight-pussy?page=2
      zoom: 2.0
- geometry: !!binary |
    AdnQywACAAAAAAAKAAAApAAAA7oAAAPyAAAACwAAAKQAAAO5AAAD8QAAAAAAAAAAB4A=
  tabs:
  - active: true
    history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Tentacle tubes :: TubeGalore'
      url: https://www.tubegalore.com/c/tentacle
      zoom: 1.9
- geometry: !!binary |
    AdnQywACAAAAAAAKAAAApAAAA7oAAAPyAAAACwAAAKQAAAO5AAAD8QAAAAAAAAAAB4A=
  tabs:
  - active: true
    history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Teen (18/19) In Gangbang tubes :: TubeGalore'
      url: https://www.tubegalore.com/c/teen-18-19-in-gangbang
      zoom: 1.9
- geometry: !!binary |
    AdnQywACAAAAAAAKAAAEPwAAA7oAAAeGAAAACwAABD8AAAd0AAEELP////8AAAAAB4A=
  tabs:
  - active: true
    history:
    - pinned: false
      title: 'Teen (18/19) tubes :: TubeGalore'
      url: https://www.tubegalore.com/c/teen-18-19
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Teen (18/19) tubes :: TubeGalore'
      url: https://www.tubegalore.com/c/teen-18-19?page=2
      zoom: 2.0
- geometry: !!binary |
    AdnQywACAAAAAAAKAAAEPwAAB3UAAQQtAAAACwAABD8AAAd0AAEELP////8AAAAAB4A=
  tabs:
  - active: true
    history:
    - pinned: false
      title: 'Teen Anal Sex (18/19) tubes :: TubeGalore'
      url: https://www.tubegalore.com/c/teen-anal-sex-18-19
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Teen Anal Sex (18/19) tubes :: TubeGalore'
      url: https://www.tubegalore.com/c/teen-anal-sex-18-19?page=2
      zoom: 1.9
- geometry: !!binary |
    AdnQywACAAAAAAPFAAAACwAAB3UAAANSAAADxgAAAAsAAAd0AAAD8QAAAAAAAAAAB4A=
  tabs:
  - active: true
    history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 1040
      title: 'Surprise tubes :: TubeGalore'
      url: https://www.tubegalore.com/c/surprise
      zoom: 1.9
- geometry: !!binary |
    AdnQywACAAAAAAAKAAAApAAAA7oAAAPyAAAACwAAAKQAAAO5AAAD8QAAAAAAAAAAB4A=
  tabs:
  - active: true
    history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 1316
      title: 'Swallow Compilation tubes :: TubeGalore'
      url: https://www.tubegalore.com/c/swallow-compilation
      zoom: 1.9
